- references.md
Added Schlund et al. (2023) to the ESMValTool "main" references.
> Added Schlund et al. (2023) to references

- _posts/2023-03-20-Workshop.md
Add news item to announce poll for next workshop date.
> News item: poll for workshop date

- _posts/2023-07-05-New-release.md
- _posts/2023-07-06-New-release.md
This pull requests posts an announcement about the new release to the website.
> Release v2.9.0 announcement

- about.md
This PR updates the general description of ESMValTool ("about"). Comments and feedback welcome!
Closes #15
> Update "about" section

- .github/issue_template.md
- .github/pull_request_template.md
Update GitHub templates for new issues and pull requests.
Closes #12
> Update GitHub templates

- _includes/footer-custom.html
- reg_publication.md
- roadmap.md
This PR updates the contact emails in the footer and the pages "roadmap" and "register your publication".
> Update contact email

- publications.md
Added study of Galytska et al., 2023 to the list of publications that used ESMValTool. Within the scope of the study, the recipe and the diagnostics were developed.
Closes #35.
Link to documentation:
[ESMValTool documentation for developed diagnostics](https://docs.esmvaltool.org/en/latest/recipes/recipe_galytska23jgr.html#recipe-galytska23jgr)
***
- [x ] [☝ Create an issue](https://github.com/ESMValGroup/ESMValTool-website/issues) to discuss what you are going to do
- [ x] Content is appropriate
- [x ] Spelling and grammar are correct
> add Galytska et al to the publications list

- publications.md
Added missing ", L." to "Bock et al. 2020" in publications.md.
> Fixed typo in publications.md (Bock et al., 2020)

- publications.md
This PR adds a the publication
`Kuhlbrodt, T., R. Swaminathan, P. Ceppi, and T. Wilder, 2024: A glimpse into the future: The 2023 ocean temperature and sea-ice extremes in the context of longer-term climate change. Bull. Amer. Meteor. Soc., https://doi.org/10.1175/BAMS-D-23-0209.1`
to the list of ESMValTool publications.
> Add paper Kuhlbrodt et al., 2024

- _posts/2024-02-05-New-paper.md
- publications.md
Added new paper Bock and Lauer (2024) to list of publications and as a news item.
> Added new paper Bock and Lauer (2024)

- acknowledgements.md
- roadmap.md
This PR updates the links to the following project websites listed in `roadmap.md` and `acknowledgements.md` that have been outdated because the website moved or the project website is no longer available:
* 4C
* APPLICATE
* CMIP6-DICAD
* CMUG
* CRESCENDO
* EMBRACE
> Update links for project websites

- _posts/2024-04-12_EGU-24.md
> Add news item for EGU2024

- _posts/2024-05-06-SHMI-job.md
Mention the ESMValTool job ad at SMHI
***
> Post job ad SMHI

- _posts/2024-07-04-New-release.md
Added a news item for the release of v2.11.0 on 4 July 2024.
> Added news item for release v2.11.0

- _includes/footer-custom.html
- terms_of_use.md
This PR adds the DLR terms of use as required by DLR regulations.
> Adding DLR terms of use

- privacy.md
Replace "information on data protection" (privacy notice) with version from DLR internet governance from 9 October 2024.
> Update privacy notice DLR 2024-10-09

- about.md
- cmip6.md
- index.html
This PR fixes the following small wording issues:
- remove "the" before "ESMValTool"
- remove "routine" from "evaluation
- add "analysis" to title page
> Fix small wording issues

- _posts/2025-02-27-New-paper.md
- publications.md
Add news item for new paper Lauer et al. (2025) and add paper to list of publications.
> Added paper Lauer et al. (2025)

- _posts/2025-03-06-New-release.md
Add news item for release of ESMValTool v2.12.0
> Add news items for release v2.12.0

- _posts/2024-12-11-Consortium_agreement.md
Closes #issue_number
Link to documentation:
***
> Fix booboo in consortium agreement post

- acknowledgements.md
Update starting date of the ESO4clima project in the acknowledgements.
> Fix ESO4clima start date
